import geometry from './logo-geometry.json';

// Official SUN MEDIA logo, drawn from the traced vector geometry shared with the mobile app
// (generated by SUNMEDIA USER/scripts/brand/generate.py).
const [W, H] = geometry.viewBox;
const ring = (points: number[][]) => `M${points.map(([x, y]) => `${x} ${y}`).join('L')}Z`;
const MEDIA = geometry.media.map((rings) => rings.map(ring).join(''));
const SUN = geometry.sun.map((line) => line.map(([x, y]) => `${x},${y}`).join(' '));

type Props = { width?: number; onDark?: boolean; compact?: boolean; className?: string };

export function Logo({ width = 140, onDark = false, compact = false, className }: Props) {
  const box = geometry.box;
  const bar = geometry.accentBar;
  const c = geometry.colors;
  const gradient = onDark ? 'sm-silver-dark' : 'sm-silver';
  return (
    <svg width={width} height={(width * H) / W} viewBox={`0 0 ${W} ${H}`} role="img" aria-label="SUN MEDIA" className={className}>
      <defs>
        <linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor={c.silverTop} />
          <stop offset="1" stopColor={c.silverBottom} />
        </linearGradient>
      </defs>
      <rect
        x={box.x}
        y={box.y}
        width={box.w}
        height={box.h}
        rx={box.r}
        fill={onDark ? '#1E1E21' : c.ink}
        stroke={onDark ? '#3A3A3E' : 'none'}
        strokeWidth={onDark ? 1.5 : 0}
      />
      <g fill="none" stroke={`url(#${gradient})`} strokeWidth={geometry.sunStroke} strokeLinejoin="round">
        {SUN.map((points) => (
          <polyline key={points} points={points} />
        ))}
      </g>
      {compact ? null : (
        <text
          x={geometry.tagline.x}
          y={geometry.tagline.y}
          fill="#C8C8CC"
          fontSize={geometry.tagline.size}
          fontWeight={600}
          letterSpacing={geometry.tagline.spacing}
          textAnchor="middle"
          fontFamily="var(--font-inter), Inter, sans-serif"
        >
          {geometry.tagline.text}
        </text>
      )}
      <g fill={onDark ? '#F4F4F5' : 'currentColor'} fillRule="evenodd">
        {MEDIA.map((d) => (
          <path key={d} d={d} />
        ))}
      </g>
      <rect x={bar.x} y={bar.y} width={bar.w} height={bar.h} fill={c.lime} />
    </svg>
  );
}
